name: Build Android APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v3
        with: { node-version: '18' }
        
      - name: Install Dependencies
        run: |
          npm init -y
          npm install -g @capacitor/cli
          npm install @capacitor/core @capacitor/android @codetrix-studio/capacitor-google-auth
          
      - name: Build Capacitor Android
        run: |
          npx cap add android
          npx cap sync android
          
      - name: Setup Google Auth for Android
        run: |
          sed -i '/<\/resources>/i \    <string name="server_client_id">868116455420-tlvb6b74tnq57vu3lorrng8bf41bjmrl.apps.googleusercontent.com</string>' android/app/src/main/res/values/strings.xml
          
      - uses: actions/setup-java@v3
        with: { distribution: 'zulu', java-version: '17' }
        
      - name: Build APK
        working-directory: ./android
        run: ./gradlew assembleDebug
        
      - uses: actions/upload-artifact@v4
        with:
          name: Quiz-Pro-App
          path: android/app/build/outputs/apk/debug/app-debug.apk
          
